-- SCRIPT SQL donné à titre indicatif. Les scripts JS ont le même effet --

BEGIN;

DROP TABLE IF EXISTS "pokemon", "type", "team", "pokemon_type", "team_pokemon";

CREATE TABLE "pokemon" (
  "id"INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "hp" INTEGER NOT NULL,
  "atk" INTEGER NOT NULL,
  "def" INTEGER NOT NULL,
  "atk_spe" INTEGER NOT NULL,
  "def_spe" INTEGER NOT NULL,
  "speed" INTEGER NOT NULL
);


CREATE TABLE "type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "color" CHAR(7) NOT NULL
);


CREATE TABLE "team" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "description" TEXT 
);


CREATE TABLE "pokemon_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pokemon_id" INTEGER NOT NULL REFERENCES "pokemon"("id"),
  "type_id" INTEGER NOT NULL REFERENCES "type"("id")
);


CREATE TABLE "team_pokemon" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pokemon_id" INTEGER NOT NULL REFERENCES "pokemon"("id"),
  "team_id" INTEGER NOT NULL REFERENCES "team"("id")
);

COMMIT;
