### Consulter la page des pokémons 
GET http://localhost:3000/pokemons

### Consulter la page d'un pokemon  
GET http://localhost:3000/pokemons/1

### Consulter la page des équipes
GET http://localhost:3000/teams
