### Consulter la page des pokémons 
GET http://localhost:3000/pokemons

### Consulter la page d'un pokemon  
GET http://localhost:3000/pokemons/1

### Consulter la page des équipes
GET http://localhost:3000/teams

### Création de team (il faut penser a sauter une ligne après le header (Content-Type: application/json)  
POST http://localhost:3000/teams
Content-Type: application/json

{
    "name": "Bad Bear Team",
    "description": "Les ours qui font mals"
}


### Modifier le nom d'une équipe
PATCH http://localhost:3000/teams/6  
Content-Type: application/json

{
    "name": "Ultra B B Team Ultimate"
}

### Récupération de tous les pokemons d'une team 
GET http://localhost:3000/team/2/pokemons

### Association d'un pokemon à une team 
PUT http://localhost:3000/teams/5/pokemons/4

### Dissociation d'un pokemon à une team 
DELETE http://localhost:3000/teams/5/pokemons/4


### Consulter la page des types 
GET http://localhost:3000/types


### Consulter la page d'un type  
GET http://localhost:3000/types/10